# -*- coding: utf-8 -*-

Author: Nagireddi Jagadesh Nischal

"""Openface_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19kGXe2rIjUTtweiOj7T6way3J2LYt3Pg
"""

## Install dependencies for OpenFace on Collab

import os
from os.path import exists, join, basename, splitext

################# Need to revert back to CUDA 10.0 ##################
# Thanks to http://aconcaguasci.blogspot.com/2019/12/setting-up-cuda-100-for-mxnet-on-google.html
#Uninstall the current CUDA version
!apt-get --purge remove cuda nvidia* libnvidia-*
!dpkg -l | grep cuda- | awk '{print $2}' | xargs -n1 dpkg --purge
!apt-get remove cuda-*
!apt autoremove
!apt-get update

#Download CUDA 10.0
!wget  --no-clobber https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
#install CUDA kit dpkg
!dpkg -i cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
!sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
!apt-get update
!apt-get install cuda-10-0
#Slove libcurand.so.10 error
!wget --no-clobber http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
#-nc, --no-clobber: skip downloads that would download to existing files.
!apt install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
!apt-get update
####################################################################

git_repo_url = 'https://github.com/TadasBaltrusaitis/OpenFace.git'
project_name = splitext(basename(git_repo_url))[0]
# clone openface
!git clone -q --depth 1 $git_repo_url

# install new CMake becaue of CUDA10
!wget -q https://cmake.org/files/v3.13/cmake-3.13.0-Linux-x86_64.tar.gz
!tar xfz cmake-3.13.0-Linux-x86_64.tar.gz --strip-components=1 -C /usr/local

# Get newest GCC
!sudo apt-get update
!sudo apt-get install build-essential 
!sudo apt-get install g++-8

# install python dependencies
!pip install -q youtube-dl

# Finally, actually install OpenFace
!cd OpenFace && bash ./download_models.sh && sudo bash ./install.sh

# /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_ Pranav/

# !cd OpenFace && bash ./download_models.sh && sudo bash ./install.sh

!/content/OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Pranav_Videos/NIR_Face.mp4' -out_dir '/content/drive/MyDrive/Pranav_Videos/' -aus

!/content/OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Pranav_Videos/Color_Face.mp4' -out_dir '/content/drive/MyDrive/Pranav_Videos/' -aus







## UNBC file name extraction and processing using Openface

import os
print(os.getcwd())

main_folders_path= '/content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/'
os.chdir(main_folders_path)
print(os.getcwd())

sub_folders= os.listdir('.')
print(sub_folders)

sub_folder_paths=[os.getcwd()+"/"+ x for x in sub_folders]
print(sub_folder_paths)

sub_folder_paths[0]

Final_commands=[]
for path in sub_folder_paths:
    current_path=path
    os.chdir(current_path)
    video_files=os.listdir('.')
    video_file_path = [str(os.getcwd())+ "/" + x for x in video_files]
    added_padding = ' -f '.join(video_file_path)
    Final_command="!/content/OpenFace/build/bin/FeatureExtraction -f "+ added_padding + " -out_dir " +str(os.getcwd())+" -aus"
    Final_commands.append(Final_command)

len(Final_commands)

print(Final_commands[0])

count=0
for cmd in Final_commands:
    print(cmd)
    # os.system(cmd)
    count+=1
    # print("Counter: ",count)



!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106/nm106t2afunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/106-nm106 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/121-vw121/vw121t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/121-vw121/vw121t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/121-vw121/vw121t1aiaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/121-vw121 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t2afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108/th108t1aeaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/108-th108 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/115-jy115/jy115t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/115-jy115/jy115t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/115-jy115/jy115t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/115-jy115/jy115t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/115-jy115/jy115t1aeaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/115-jy115 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/123-jh123/jh123t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/123-jh123/jh123t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/123-jh123/jh123t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/123-jh123/jh123t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/123-jh123/jh123t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/123-jh123/jh123t1afaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/123-jh123 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107/hs107t1afunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/107-hs107 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120/kz120t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120/kz120t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120/kz120t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120/kz120t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120/kz120t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120/kz120t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120/kz120t1afunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/120-kz120 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109/ib109t1aeaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/109-ib109 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103/jk103t1aeaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/103-jk103 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124/dn124t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124/dn124t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124/dn124t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124/dn124t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124/dn124t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124/dn124t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124/dn124t1aiaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/124-dn124 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t2afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097/gf097t2aiaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/097-gf097 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066/mg066t2aaunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/066-mg066 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/092-ch092/ch092t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/092-ch092/ch092t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/092-ch092/ch092t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/092-ch092/ch092t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/092-ch092/ch092t2aaaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/092-ch092 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052/dr052t2aeunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/052-dr052 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080/bn080t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080/bn080t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080/bn080t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080/bn080t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080/bn080t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080/bn080t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080/bn080t1aeunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/080-bn080 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/059-fn059/fn059t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/059-fn059/fn059t2afunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/059-fn059 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101/mg101t2afaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/101-mg101 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/064-ak064/ak064t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/064-ak064/ak064t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/064-ak064/ak064t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/064-ak064/ak064t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/064-ak064/ak064t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/064-ak064/ak064t1aiaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/064-ak064 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/095-tv095/tv095t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/095-tv095/tv095t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/095-tv095/tv095t2aeunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/095-tv095 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096/bg096t2afunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/096-bg096 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048/aa048t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048/aa048t2aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048/aa048t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048/aa048t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048/aa048t2afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048/aa048t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048/aa048t2aaunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/048-aa048 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t2afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049/bm049t2aeunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/049-bm049 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t2afaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047/jl047t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047/jl047t1aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047/jl047t1afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047/jl047t1aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047/jl047t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047/jl047t1aiaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047/jl047t1aiunaff.avi -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/047-jl047 -aus

!/content/OpenFace/build/bin/FeatureExtraction -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t2aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t2aaaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t2aeunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t1afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t2aiunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t2afunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t2aaunaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t1aeaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/jh043t2afaff.avi -f /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043/processed -out_dir /content/drive/MyDrive/UNBC_OF/UNBC_Created_Videos_Pranav/043-jh043 -aus




# with open('/content/drive/MyDrive/Colab Notebooks/ll042t1aaaff.avi', 'r') as v:
# !./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/071911_w_24.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus

!./OpenFace/build/bin/FeatureExtraction -f /content/drive/My Drive/UNBC_OF/UNBC_Created_Videos_Pranav/042-ll042/ll042t1aaaff.avi

!./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Pranav_Videos/IMG_0267.mp4' -out_dir '/content/drive/MyDrive/Pranav_Videos/' -aus

!./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Pranav_Videos/IMG_0268.mp4' -out_dir '/content/drive/MyDrive/Pranav_Videos/' -aus



!./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/071614_m_20.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus

# !./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/081014_w_27.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus

# !./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/080309_m_29.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus

# !./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/072414_m_23.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus
#

# !./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/072514_m_27.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus

# !./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/072609_w_23.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus

# !./OpenFace/build/bin/FeatureExtraction -f '/content/drive/MyDrive/Colab Notebooks/072714_m_23.mp4' -out_dir '/content/drive/MyDrive/Colab Notebooks/' -aus

