# This file is locked for security reasons. Contact { pdeo@bententech.com } for access privileges.
mysql_host: 'impact.cgwrhxgkrj1c.us-east-1.rds.amazonaws.com'
mysql_user: 'admin'
mysql_password: 'admin123'
mysql_db: 'impact'
mysql_port: 3306
