export const AUTH_ACTIONS = {
  RESTORE_TOKEN: 'RESTORE_TOKEN',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SKIP_ONBOARDING: 'SKIP_ONBOARDING',
  SHOW_ONBOARDING: 'SHOW_ONBOARDING',
};

export const USER_ACTIONS = {
  UPDATE_AUTH_DATA: 'UPDATE_AUTH_DATA',
};

export const PATIENT_ACTIONS = {
  ADD_PATIENT: 'ADD_PATIENT',
};
export const ROUTE_NAME_ACTION= {
  ROUTE_NAME : 'ROUTE NAME'
}

export const PAIN_ASSESSMENT_DATA_ACTION = {
  PAIN_ASSESSMENT_DATA: 'PAIN_ASSESSMENT_DATA',
};

export const ALL_PATIENTS_ACTIONS = {
  ALL_PATIENTS: ' ALL_PATIENTS',
};

export const LOOKUP_DATA_ACTION = {
  LOOKUP_DATA: 'LOOKUP_DATA',
};

export const LOOKUP_TYPE_ACTION = {
  LOOKUP_TYPE: ' LOOKUP_TYPE',
};

export const PATIENT_NAME_ACTION = {
  PATIENT : 'PATIENT'
}

export const CREATE_ASSESSMENT_ACTION = {
  CREATE_ASSESSMENT : "CREATE ASSESSMENT"
}

export const CREATE_MEDICATION_ACTION={
  CREATE_MEDICATION:"CREATE MEDICATION"
}

export const GET_ASSESSMENT_ACTION ={
  GET_ASSESSMENT : 'GET ASSESSMENT'
}

export const ALL_ASSESSMENTS_LIST_ACTION={
  ALL_ASSESSMENT_LIST : "ALL ASSESSMENT LIST"
}

export const envActions = {
  SET_ENVIRONMENT: "setEnvironment"
}
export const PAIN_LOCATIONS_ACTION ={
  PAIN_LOCATION : 'SET PAIN LOCATION'
}
export const LATEST_ENTRY_ACTION = {
  LATEST_ENTRY:"LATEST ENTRY"

}