export const AUTH_ACTIONS = {
    RESTORE_TOKEN: "RESTORE_TOKEN",
    SIGN_IN: "SIGN_IN",
    SIGN_OUT: "SIGN_OUT",
    SKIP_ONBOARDING: "SKIP_ONBOARDING",
    SHOW_ONBOARDING: "SHOW_ONBOARDING"
}

export const USER_ACTIONS = {
    UPDATE_AUTH_DATA: "UPDATE_AUTH_DATA"
}