# This file is locked for security reasons. Contact { pdeo@bententech.com } for access privileges.
mysql_host: 'impact.cgwrhxgkrj1c_xxxxxxxxxxxxxxxxx.us-east-?.rds.amazonaws.com'
mysql_user: '?????'
mysql_password: '?????'
mysql_db: '(-|-)'
mysql_port: 1010
